twig:
    default_path: '%kernel.project_dir%/templates'

    # activation du thème Bootstrap 5 pour les formulaires
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:

        # Récupération du nom du site dans le fichier services.yaml
        site_name: '%app.site_name%'

        # Récupération de la clé publique Google Recaptcha depuis le fichier services.yaml
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

        # Récupération du repository des catégories pour l'intégrer en base.html.twig
        category_repo: '@App\Repository\CategoryRepository'

when@test:
    twig:
        strict_variables: true